<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="RealTimeWebApp.Default" %>

<html>
<head>
    <title>AzureGuidance RealTimeIOTProcessor</title>
    <style type="text/css">
        /*.container {
            background-color: #99CCFF;
            border: thick solid #808080;
            padding: 20px;
            margin: 20px;
           
        }*/
        html {
            height: 100%;
        }

        body {
            height: 100%;
            margin: 0;
            padding: 0;
        }

        #map_canvas {
            height:639px;
            width:800px;
            border: thick solid #808080;
            padding: 20px;
            margin: 20px;
           
        }
        
        .navbar-default {
            height: 19px;
        }
        .navbar-default {
            height: 30px;
        }
        
    </style>
    <link href="Content/bootstrap.min.css" rel="stylesheet" media="screen">  
</head>
<body>
    <form id="form1" runat="server">
        <nav class="navbar navbar-default navbar-fixed-top"  role="navigation">
             <div class="container" >
        <div class="navbar-header" >
            <p class="navbar-text" >RealTime IoT Tracker</p> </div></div>
            </nav>
        <div style="margin-top:50px">
            <table class="table-responsive">
                <tr>
                    <td>
                        <div id="map_canvas">
                        </div>
                    </td>
                    <td>
                        <table>
                            <tr><th>GPSPosition</th></tr>
                            <tr>
                                <td>
                                    <div class="well sidebar-nav">
                                        <ul id="discussion" class="nav">
                                        </ul>

                                    </div>
                                </td>
                            </tr>
                        </table>
                </td>
            </table>
        </div>
    <!--Reference the jQuery library. -->
    <script src="Scripts/jquery-2.1.3.js"></script>
    <script src="Scripts/jquery-2.1.3.min.js"></script>
    <!--Reference the SignalR library. -->
    <script src="Scripts/jquery.signalR-2.2.0.js"></script>
    <script src="Scripts/jquery.signalR-2.2.0.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="/signalr/hubs"></script>
    <script src="Scripts/bootstrap.min.js"></script>  
    <!--Add script to update the page and send messages.--> 
    <script type="text/javascript">
        var map = null;
        var poly;

        $(function () {

            // Declare a proxy to reference the hub. 
            var receiver = $.connection.azureGuidanceEventHubReceiver;
            receiver.client.displayMyMessage = function (data) {
                // Html encode display data 
                //debugger;
                var encodedData = $('<div />').text(data.GPSPosition).html();
                var data = encodedData.split("\n");
                var varlat = data[0].replace("Latitude:", "").trim();
                var varlong = data[1].replace("Longitude:", "").trim();
                ShowInGoogleMap(varlat, varlong);
                $('#discussion').append('<li>' + encodedData + '</li>');

            };
           
            // Start the connection.
            $.connection.hub.start().done(function () {
               receiver.server.processEvents();
               });
            
        });

       
    </script>
         
        <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?&sensor=false">
        </script>
        <script type="text/javascript">
            function ShowInGoogleMap(latitude, longitude) {
                var myLatlng = new google.maps.LatLng(latitude, longitude)
               
                var mapOptions = {
                    center: myLatlng,
                    zoom: 18,
                    mapTypeId: google.maps.MapTypeId.ROADMAP,
                    marker: true
                };
                var mapCanvas = document.getElementById("map_canvas");
                if (mapCanvas) {
                    if (!map) {
                        map = new google.maps.Map(mapCanvas, mapOptions);
                        var polyOptions = {
                            strokeColor: '#1092E3',
                            strokeOpacity: 1.0,
                            strokeWeight: 7
                        };
                        poly = new google.maps.Polyline(polyOptions);
                        poly.setMap(map);

                    }
                    var marker = new google.maps.Marker({
                        position: myLatlng,
                        icon: {
                            path: google.maps.SymbolPath.CIRCLE,
                            scale: 3,
                            strokeColor: '#A82B13'
                        },

                        map: map
                       
                    });
                    map.setCenter(marker.getPosition());

                    var path = poly.getPath();
                    path.push(myLatlng);
                   
                }
            }
        </script>
    </form>
    
</body>
</html>